version: "3.8"

services:
  app:
    # Changed: Pulling the image from AWS ECR instead of building locally
    image: "${AWS_ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:latest"
    container_name: auth_app
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass@4523
      POSTGRES_DB: mynodeapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
